using System;
using System.Collections.Generic;
using ProERP.Core;

namespace ProERP.Data.Models
{
    public partial class TemplateMapping : BaseEntity
    {
        public int TemplateId { get; set; }
        public string SystemColumnName { get; set; }
        public string ColumnName { get; set; }
        public string DataType { get; set; }
        public string GroupName { get; set; }
        public int OrderNo { get; set; }
        public string Formula { get; set; }
        public bool IsRequired { get; set; }
        public bool IsAggregate { get; set; }
        public string AggregateFunction { get; set; }
        public Nullable<int> FixColumnId { get; set; }
        public bool IsSearchColumn { get; set; }
        public bool IsEditable { get; set; }
        public string OnChangeFormula { get; set; }
        public int Width { get; set; }
        public bool IsAutoGenerated { get; set; }
        public bool IsOrderBy { get; set; }
        public string DefaultValue { get; set; }
        public virtual TemplateFixColumn TemplateFixColumn { get; set; }
        public virtual Template Template { get; set; }
    }
}
